//@version=2
study('Preprocessor example')
//if close > open // This line has one indent
//    x + y // This line has two indents
//else 
//    x - y

fun(x, y) =>
    if close > open // This line has one indent
        x + y // This line has two indents
        x + y // This line has two indents
    else 
        x - y
    // Some whitespace and a comment
//
a = sma(close, 10)
b = fun(a, 123)
c = security(tickerid, period, b)
//c = security(tickerid, k='v')
plot(c, title='Out', color=c > c[1] ? lime : red, // This statement will be continued on the next line
     style=linebr, trackprice=true) // It's prefixed with 5 spaces, so it won't be considered as an indent
//alertcondition(c > 100)
