//@version=3
strategy("DOTENKUN (UKI Ver.)", overlay=true, initial_capital=10000, default_qty_type=strategy.percent_of_equity, default_qty_value=100, currency=currency.USD, commission_type=strategy.commission.percent, commission_value=0.0675)

length    = input(title="Length", type=integer, minval=1, maxval=1000, defval=5)
k         = input(title="K", type=float, minval=1, maxval=1000, defval=1.6, step=0.1)

range = 0.0
for i = 1 to length
    range := range + tr[i]
range := range / length * k

if (not na(close[length]))
    if (close > open and tr > range)
        strategy.entry("Long", strategy.long,  comment="Long")
    if (open > close and tr > range)
        strategy.entry("Short", strategy.short, comment="Short")

upBound = open + range
downBound = open - range
plot(upBound,   title="upBound",   color=green, linewidth=2, style=line)
plot(downBound, title="downBound", color=red,   linewidth=2, style=line)
